//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.4.4
//     from Assets/_Scripts/InputSystem/PlayerInput.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @PlayerInput : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @PlayerInput()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""PlayerInput"",
    ""maps"": [
        {
            ""name"": ""PlayerControlOnGround"",
            ""id"": ""4ebb4f94-23d5-4bf7-ab9e-350208642e6b"",
            ""actions"": [
                {
                    ""name"": ""Move"",
                    ""type"": ""Value"",
                    ""id"": ""d1112180-a092-4679-8498-06701a4bd335"",
                    ""expectedControlType"": ""Stick"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""ef7b4c63-b12c-4c5d-a210-b349d9d16f56"",
                    ""path"": ""<Gamepad>/leftStick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // PlayerControlOnGround
        m_PlayerControlOnGround = asset.FindActionMap("PlayerControlOnGround", throwIfNotFound: true);
        m_PlayerControlOnGround_Move = m_PlayerControlOnGround.FindAction("Move", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // PlayerControlOnGround
    private readonly InputActionMap m_PlayerControlOnGround;
    private IPlayerControlOnGroundActions m_PlayerControlOnGroundActionsCallbackInterface;
    private readonly InputAction m_PlayerControlOnGround_Move;
    public struct PlayerControlOnGroundActions
    {
        private @PlayerInput m_Wrapper;
        public PlayerControlOnGroundActions(@PlayerInput wrapper) { m_Wrapper = wrapper; }
        public InputAction @Move => m_Wrapper.m_PlayerControlOnGround_Move;
        public InputActionMap Get() { return m_Wrapper.m_PlayerControlOnGround; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(PlayerControlOnGroundActions set) { return set.Get(); }
        public void SetCallbacks(IPlayerControlOnGroundActions instance)
        {
            if (m_Wrapper.m_PlayerControlOnGroundActionsCallbackInterface != null)
            {
                @Move.started -= m_Wrapper.m_PlayerControlOnGroundActionsCallbackInterface.OnMove;
                @Move.performed -= m_Wrapper.m_PlayerControlOnGroundActionsCallbackInterface.OnMove;
                @Move.canceled -= m_Wrapper.m_PlayerControlOnGroundActionsCallbackInterface.OnMove;
            }
            m_Wrapper.m_PlayerControlOnGroundActionsCallbackInterface = instance;
            if (instance != null)
            {
                @Move.started += instance.OnMove;
                @Move.performed += instance.OnMove;
                @Move.canceled += instance.OnMove;
            }
        }
    }
    public PlayerControlOnGroundActions @PlayerControlOnGround => new PlayerControlOnGroundActions(this);
    public interface IPlayerControlOnGroundActions
    {
        void OnMove(InputAction.CallbackContext context);
    }
}
